version: '3'

services:
    web:
      image: nginx:alpine
      container_name: nginx
      ports:
            - "8000:80"
      volumes:
            - .:/guestbook
            - ./Config:/etc/nginx/conf.d
      networks:
            - nginxphp

    php:
      image: php:7.3-fpm-alpine
      container_name: guestbookphp
      volumes:
            - .:/guestbook   
      expose:
            - 9000
      networks:
            - nginxphp


networks:
    nginxphp: